### PR TITLE
When exception catched,make sure console application can show the exception

### PR DESCRIPTION
**Pull request by chucklu**
add   Console.ReadLine() for every Console Application Example

### CODE REVIEW

**Comment by chucklu** [comment]
？any complain？
in the console application,have you tested when you catch an exception?

**Comment by masroore** [comment]
@chucklu Thanks for the contribution. I've relocated the ReadLine() method inside the `catch{}` block

**Comment by chucklu** [comment]
actually,put the ReadLine() outside the catch is better
 Curl.GlobalCleanup();
then exit the application ?
actually,I want to see what I have get which should be showd on Console

**Comment by masroore** [comment]
These are very simple console demos and are supposed to be run inside a command line environment. The purpose of these simple apps is to demonstrate the capabilities of the library. That's why I'd like to keep them lean. Also take note that these apps are almost line-by-line C# port of the official libcURL samples. You don't want to deviate too much from the source.

**Comment by chucklu** [comment]
ok,I always run the console application in Debug mode rather than command line environment

**Pull request closed without merging**
